#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Game\BattlingCommand;


$application = new Application();

$application->addCommands([
    new BattlingCommand()
]);

$application->run();