#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Game\WarCommand;

$application = new Application();

$application->addCommands([
    new WarCommand()
]);

$application
    ->setDefaultCommand('war', true)
    ->run();